### PR TITLE
Fix a bug about string splicing

### PR DESCRIPTION
**Pull request by captain686**
Fix the error "An exception has occurred: can only concatenate str (not "NoneType") to str" when the bevigil api lacks the key

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
Thanks for this, can you have a look at the metals module please and copy that for the api key if statement, then will merge it in☺️ much appreciated this fix

**Comment by captain686** [comment]
> 谢谢你，您能看一下 Metals 模块吗？并复制它作为 api key if 语句，然后将其合并到☺️非常感谢这个修复

Sorry, I don't understand what you mean by metal modules? Could you please explain it to me, thank you very much😊

**Comment by captain686** [comment]
> Thanks for this, can you have a look at the metals module please and copy that for the api key if statement, then will merge it in☺️ much appreciated this fix

Sorry, I don't understand what you mean by metals module? Could you please explain it to me, thank you very much😊

**Comment by L1ghtn1ng** [comment]
Apologies, autocorrect changed it, this is the module I was on about netlas.py

**Comment by captain686** [comment]
Is there anything else I need to do?😀

**Comment by L1ghtn1ng** [comment]
Yeah copy the if statement from that module as that is what it is meant to be for missing api keys

**Pull request merged**
