### PR TITLE
Clean up & missing items.

### PR DESCRIPTION
**Pull request by leebaird**

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
Is the -a in line 9 in theHarvester.py a typo?

**Comment by leebaird** [comment]
No, I was trying implement a new versioning system.

**Comment by NotoriousRebel** [comment]
In regards to the examples given there are two problems I noticed:

you can't to python3 theHarvester.py -d acme.com -b google -l 200 -g 
As once it sees -b it will start the query with the default limit of 500 and ignore the -g flag 
to work properly you would need to do python3 theHarvester.py -d acme.com -l 200 -g -b google
the problem with putting -b *search engine* before -l is in other examples well.

**Comment by laramies** [comment]
@leebaird  Any chance you can resubmit after I merge latest PR that doesnt conflict and fix also many of the stuff you spotted?

**Comment by leebaird** [comment]
I just copied the new code from censysparser.py and stash.py and added it to mine. Those 2 files should now be ok.

**Comment by NotoriousRebel** [comment]
@leebaird Have you tested these changes?

**Comment by leebaird** [comment]
Yes!

**Comment by laramies** [comment]
I merged them manually and solved conflicts.

**Pull request closed without merging**
