### PR TITLE
Fix ModuleNotFoundError on install.

### PR DESCRIPTION
**Pull request by onrik**
Fix this problem on package install.
```bash
python setup.py install
Traceback (most recent call last):
  File "/home/onrik/Workspace/theHarvester-3.2.4/setup.py", line 2, in <module>
    from theHarvester.lib.core import Core
  File "/home/onrik/Workspace/theHarvester-3.2.4/theHarvester/lib/core.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
This PR will not fix that issue as you are just missing a library which can be fixed if you run the install for the dependencies

**Comment by onrik** [comment]
But dependencies should installs due `setup.py install`

**Comment by L1ghtn1ng** [comment]
What OS you using?
________________________________

**Comment by onrik** [comment]
Debian buster.

**Pull request closed without merging**
