### PR TITLE
Updated zoomeye module, updated user agents list, fixed substring not found, and replaced orjson in favor of ujson.

### LINKED ISSUE #764: [substring not found] Says "substring not found" and shows no info
Hello!  I ran The Harvester one time, and it correctly gave me the information.  However, when I went ran it again, it said "substring not found," and it showed empty tables after the search.  I am using Kali Linux.  How can I fix this?  Thank you!

### PR DESCRIPTION
**Pull request by NotoriousRebel**
* Added a function to query subdomains for a given domain via [API endpoint](https://www.zoomeye.org/doc#search-sub-domain-ip) into Zoomeye module.
* Updated list of user agents to be of [most popular user agents](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/)
* Fixed #764
* Replaced orjson with ujson to remove dependency on Rust

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
Missed adding ujson to base.txt or is that a built in standard library?

**Comment by L1ghtn1ng** [comment]
Plus you have a flake8 error

**Comment by NotoriousRebel** [comment]
@L1ghtn1ng Ujson is within base.txt as well as within dev.txt for the types. I have also resolved the flake8 errors.

**Comment by L1ghtn1ng** [comment]
So it is missed that

**Pull request merged**
