### PR TITLE
PR: discovery with Qwant search engine

### PR DESCRIPTION
**Pull request by KernelPan1k**
Hello, I had Qwant search engine to the discovery list, thank you for your great tool !!

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
Thank you for the PR, I will review this soon.

**Comment by L1ghtn1ng** [comment]
Thanks for the kind words and PR, can you please create a unit test for it with pytest and also add static typing so it can be checked with mypy please

**Comment by KernelPan1k** [comment]
Yeah, sure, I'll write some tests tomorrow.

**Comment by KernelPan1k** [comment]
Hi, would you like me to edit this file too?

https://github.com/laramies/theHarvester/blob/master/.github/workflows/theHarvester.yml

**Comment by L1ghtn1ng** [comment]
Yes please
________________________________

**Comment by L1ghtn1ng** [comment]
Thanks for the PR and nice job on this PR

**Comment by KernelPan1k** [comment]
Thank you very much

**Comment by L1ghtn1ng** [comment]
@KernelPan1k can you have a look at this please ? ```[*] Target: yale.edu 
 
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=70&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=20&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=40&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=280&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=380&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=130&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=160&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
An exception has occurred: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.qwant.com/api/search/web?count=10&offset=150&q=%C2%AB@yale.edu%C2%BB&t=web&r=US&device=desktop&safesearch=0&locale=en_US&uiv=4')
[{'title': 'Yale University', 'favicon': '//s.qwant.com/fav/y/a/www_yale_edu.ico', 'url': 'https://www.yale.edu/', 'source': 'https://www.<b>yale.edu</b>', 'desc': 'Yale quantum researchers create an error-correcting cat August 12, 2020 Yale aligns procedures for addressing sexual misconduct with new U.S. rules August 12, 2020 Strong link found between abnormal liver tests and poor COVID-19 outcomes August 6, 2020 Taking your ‘mental health temperature’ during COVID-19 August 5, 2020', '_id': '3916364184fda6831c15f70f7e641f79', 'score': 0, 'position': 1}, {'title': 'Yale Forklifts: World leaders in forklifts &amp; warehousing ...', 'favicon': '//s.qwant.com/fav/y/a/www_yale_com.ico', 'url': 'https://www.yale.com/', 'source': 'https://www.yale.com', 'desc': 'YALE, the Lift Truck Icon, VERACITOR, the Yale ECO Logo, PEOPLE. PRODUCTS. PRODUCTIVITY., PREMIER, UNISOURCE, HI-VIS, CSS, MATERIALS HANDLING CENTRAL and MATERIAL HANDLING CENTRAL are trademarks, service marks or registered marks in the United States and certain other jurisdictions. The Lift Truck Icon and the Yale ECO Logo are also protected ...', '_id': '715958baf3208a57c9849659ca90c322', 'score': 0, 'position': 2}, {'title': 'news.<b>yale.edu</b> - YaleNews | Home', 'favicon': '//s.qwant.com/fav/y/a/news_yale_edu.ico', 'url': 'https://news.yale.edu/', 'source': 'https://news.<b>yale.edu</b>', 'desc': 'Yale is committed to educating a student body “whose diversity is a mark of its excellence,” President Peter Salovey responded to a DOJ letter about admissions. Yale quantum researchers create an error-correcting cat. Yale aligns procedures for addressing sexual misconduct with new U.S. rules.', '_id': 'd687a5deba04f472f9c4d27b8d085e65', 'score': 0, 'position': 3}, {'title': 'Yale University - Wikipedia', 'favicon': '//s.qwant.com/fav/w/i/en_wikipedia_org.ico', 'url': 'https://en.wikipedia.org/wiki/Yale_University', 'source': 'https://en.wikipedia.org/wiki/Yale_University', 'desc': "Yale University is a private Ivy League research university in New Haven, Connecticut.Founded in 1701 as the Collegiate School, it is the third-oldest institution of higher education in the United States and one of the nine Colonial Colleges chartered before the American Revolution.Collegiate School was renamed Yale College in 1718 to honor the school's largest benefactor, Elihu Yale.", '_id': 'b74d7c1fd691607d7caffb1da6608a02', 'score': 0, 'position': 4}, {'title': "Yale can't discriminate against Jews and Asians and expect ...", 'favicon': '//s.qwant.com/fav/n/y/nypost_com.ico', 'url': 'https://nypost.com/2020/08/15/yale-cant-discriminate-against-jews-and-asians-and-expect-taxpayer-money/', 'source': 'https://nypost.com/2020/08/15/yale-cant-discriminate-against-jews-and-asians-and-expect...', 'desc': 'The Justice Department has ordered Yale to stop discriminating on the basis of race in admissions, against Jews and Asians and in favor of blacks and Latinos, a violation of the federal Civil ...', '_id': 'f5f907c8369fd038e14b3563f3fdf4c4', 'score': 0, 'position': 5}, {'title': 'About Yale | Yale University', 'favicon': '//s.qwant.com/fav/y/a/www_yale_edu.ico', 'url': 'https://www.yale.edu/about-yale', 'source': 'https://www.<b>yale.edu</b>/about', 'desc': 'Yale’s reach is both local and international. It partners with its hometown of New Haven, Connecticut to strengthen the city’s community and economy. And it engages with people and institutions across the globe in the quest to promote cultural understanding, improve the human condition, delve more deeply into the secrets of the universe, and train the next generation of world', '_id': '4561946c1d247a42674c12dca2939c04', 'score': 0, 'position': 6}, {'title': 'DOJ accuses Yale of discriminating against Asian American ...', 'favicon': '//s.qwant.com/fav/g/o/abcnews_go_com.ico', 'url': 'https://abcnews.go.com/US/doj-accuses-yale-discriminating-asian-american-white-applicants/story?id=72360245', 'source': 'https://abcnews.go.com/US/doj-accuses-yale-discriminating-asian-american-white...', 'desc': 'The Department of Justice has accused Yale University of illegally discriminating against Asian American and white applicants. A two-year civil rights investigation, in response to a complaint by ...', '_id': 'e103837685662e414325470c4d29f327', 'score': 0, 'position': 7}, {'title': 'DOJ: Yale guilty of admissions discrimination against ...', 'favicon': '//s.qwant.com/fav/h/o/hotair_com.ico', 'url': 'https://hotair.com/archives/john-s-2/2020/08/13/doj-accuses-yale-admissions-discrimination-asians-whites/', 'source': 'https://hotair.com/archives/john-s-2/2020/08/13/doj-accuses-yale-admissions...', 'desc': 'The Civil Rights Division of the Department of Justice notified Yale today that it is violating Title VI of the 1964 Civil Rights Act by discriminating against Asian and white Americans in undergraduate admissions.. The Department of Justice found Yale discriminates based on race and national origin in its undergraduate admissions process, and that race is the determinative factor in hundreds ...', '_id': 'adfc4a66853d16a2ac4e37ba153d0567', 'score': 0, 'position': 8}, {'title': 'Yale’s rapid COVID-19 saliva test receives FDA emergency ...', 'favicon': '//s.qwant.com/fav/f/o/www_foxnews_com.ico', 'url': 'https://www.foxnews.com/health/yales-rapid-covid-19-saliva-test-receives-fda-emergency-use-authorization', 'source': 'https://www.foxnews.com/health/yales-rapid-covid-19-saliva-test-receives-fda-emergency...', 'desc': "A new saliva-based laboratory diagnostic test for the novel coronavirus developed by researchers at Yale University's School of Public Health has been granted an emergency use authorization by the ...", '_id': '666138578541d81ee98f0664f1aa4f1b', 'score': 0, 'position': 9}, {'title': 'Yale’s rapid COVID-19 saliva test receives FDA emergency ...', 'favicon': '//s.qwant.com/fav/y/a/news_yale_edu.ico', 'url': 'https://news.yale.edu/2020/08/15/yales-rapid-covid-19-saliva-test-receives-fda-emergency-use-authorization', 'source': 'https://news.<b>yale.edu</b>/2020/08/15/yales-rapid-covid-19-saliva-test-receives-fda...', 'desc': 'A saliva-based laboratory diagnostic test developed by researchers at the Yale School of Public Health to determine whether someone is infected with the novel coronavirus has been granted an emergency use authorization by the U.S. Food and Drug Administration (FDA). The method, called SalivaDirect ...', '_id': '1e84635437c4402cc7c4783c7f0529e3', 'score': 0, 'position': 10}]
[{'title': "Yale can't discriminate against Jews and Asians and expect ...", 'favicon': '//s.qwant.com/fav/n/y/nypost_com.ico', 'url': 'https://nypost.com/2020/08/15/yale-cant-discriminate-against-jews-and-asians-and-expect-taxpayer-money/', 'source': 'https://nypost.com/2020/08/15/yale-cant-discriminate-against-jews-and-asians-and-expect...', 'desc': 'The Justice Department has ordered Yale to stop discriminating on the basis of race in admissions, against Jews and Asians and in favor of blacks and Latinos, a violation of the federal Civil ...', '_id': 'f5f907c8369fd038e14b3563f3fdf4c4', 'score': 0, 'position': 1}, {'title': 'Yale’s rapid COVID-19 saliva test receives FDA emergency ...', 'favicon': '//s.qwant.com/fav/f/o/www_foxnews_com.ico', 'url': 'https://www.foxnews.com/health/yales-rapid-covid-19-saliva-test-receives-fda-emergency-use-authorization', 'source': 'https://www.foxnews.com/health/yales-rapid-covid-19-saliva-test-receives-fda-emergency...', 'desc': "A new saliva-based laboratory diagnostic test for the novel coronavirus developed by researchers at Yale University's School of Public Health has been granted an emergency use authorization by the ...", '_id': '666138578541d81ee98f0664f1aa4f1b', 'score': 0, 'position': 2}, {'title': 'Yale’s rapid COVID-19 saliva test receives FDA emergency ...', 'favicon': '//s.qwant.com/fav/y/a/news_yale_edu.ico', 'url': 'https://news.yale.edu/2020/08/15/yales-rapid-covid-19-saliva-test-receives-fda-emergency-use-authorization', 'source': 'https://news.<b>yale.edu</b>/2020/08/15/yales-rapid-covid-19-saliva-test-receives-fda...', 'desc': 'A saliva-based laboratory diagnostic test developed by researchers at the Yale School of Public Health to determine whether someone is infected with the novel coronavirus has been granted an emergency use authorization by the U.S. Food and Drug Administration (FDA). The method, called SalivaDirect ...', '_id': '1e84635437c4402cc7c4783c7f0529e3', 'score': 0, 'position': 3}, {'title': 'us.yalehome.com - Yale US', 'favicon': '//s.qwant.com/fav/y/a/us_yalehome_com.ico', 'url': 'https://us.yalehome.com/en/', 'source': 'https://us.yalehome.com', 'desc': 'Yale Home - trusted every day', '_id': '769d829ca2cb7ec97f174056f0fdbfb5', 'score': 0, 'position': 4}, {'title': 'DOJ: Yale guilty of admissions discrimination against ...', 'favicon': '//s.qwant.com/fav/h/o/hotair_com.ico', 'url': 'https://hotair.com/archives/john-s-2/2020/08/13/doj-accuses-yale-admissions-discrimination-asians-whites/', 'source': 'https://hotair.com/archives/john-s-2/2020/08/13/doj-accuses-yale-admissions...', 'desc': 'The Civil Rights Division of the Department of Justice notified Yale today that it is violating Title VI of the 1964 Civil Rights Act by discriminating against Asian and white Americans in undergraduate admissions.. The Department of Justice found Yale discriminates based on race and national origin in its undergraduate admissions process, and that race is the determinative factor in hundreds ...', '_id': 'adfc4a66853d16a2ac4e37ba153d0567', 'score': 0, 'position': 5}, {'title': 'DOJ accuses Yale of discriminating against Asian American ...', 'favicon': '//s.qwant.com/fav/g/o/abcnews_go_com.ico', 'url': 'https://abcnews.go.com/US/doj-accuses-yale-discriminating-asian-american-white-applicants/story?id=72360245', 'source': 'https://abcnews.go.com/US/doj-accuses-yale-discriminating-asian-american-white...', 'desc': 'The Department of Justice has accused Yale University of illegally discriminating against Asian American and white applicants. A two-year civil rights investigation, in response to a complaint by ...', '_id': 'e103837685662e414325470c4d29f327', 'score': 0, 'position': 6}, {'title': 'COVID-19: Yale Actions and Response', 'favicon': '//s.qwant.com/fav/y/a/covid19_yale_edu.ico', 'url': 'https://covid19.yale.edu/', 'source': 'https://covid19.<b>yale.edu</b>', 'desc': 'Returning to Yale: The Academic Year Ahead. Updated August 12, 2020. President Peter Salovey and Provost Scott Strobel announced on July 1 that Yale will welcome graduate and professional school students and a portion of the undergraduate population back to campus for the fall semester. The reactivation of campus-based research is under way already.', '_id': 'c0a38b2d5189da8effa1b48875a9f57a', 'score': 0, 'position': 7}, {'title': 'Justice Department finds Yale biased against Asian, white ...', 'favicon': '//s.qwant.com/fav/n/h/www_nhregister_com.ico', 'url': 'https://www.nhregister.com/news/article/Justice-Department-finds-Yale-biased-against-15482269.php', 'source': 'https://www.nhregister.com/news/article/Justice-Department-finds-Yale-biased-against...', 'desc': 'Yale uses race at multiple steps of its admissions process, resulting in a multiplied effect of race on an applicant’s likelihood of admission, and Yale racially balances its classes, the ...', '_id': 'fdda32203a08531b2e4738377d6cc97c', 'score': 0, 'position': 8}, {'title': 'Products - Yale US', 'favicon': '//s.qwant.com/fav/y/a/www_yalehome_com.ico', 'url': 'https://www.yalehome.com/en/products/', 'source': 'https://www.yalehome.com/en/products', 'desc': 'The Yale Pro™ SL is a key-free touchscreen deadbolt with Z-Wave Plus built-in, offered through our pro channels. Yale Smart Storage. Our smart delivery and storage product line includes the Yale Smart Delivery Box, Yale Smart Cabinet Lock and Yale Smart Safe. All three products will be compatible with a new Yale Access app and...', '_id': '6056b6ab45880e3b9f6ba33054211641', 'score': 0, 'position': 9}, {'title': 'Yale® Locks &amp; Hardware - ASSA ABLOY', 'favicon': '//s.qwant.com/fav/y/a/www_yalecommercial_com.ico', 'url': 'https://www.yalecommercial.com/en/', 'source': 'https://www.yalecommercial.com', 'desc': "Linus Yale Jr. transformed the locking industry forever when he created his most important invention -- the Yale pin tumbler cylinder. One hundred and fifty years later, Yale's comprehensive line of door hardware includes mortise and cylindrical locks, exit devices, door closers, electromechanical products and key systems.", '_id': 'e24ae5840075b064012611e1bc8a5985', 'score': 0, 'position': 10}]

```
Also running the test I am getting 
```
        for response in responses:
            try:
>               response_items = response['data']['result']['items']
E               TypeError: string indices must be integers

theHarvester/discovery/qwantsearch.py:51: TypeError

```

**Comment by KernelPan1k** [comment]
Yeah, I was watching that earlier.

**Pull request merged**
