### PR TITLE
fix(censys): update module

### LINKED ISSUE #1468: [Bug] Censys needs porting to the new api version
@thehappydinoa You able to please update censys to the new api in theHarvester please?

### PR DESCRIPTION
**Pull request by thehappydinoa**
Closes #1468

### CODE REVIEW

**Comment by thehappydinoa** [comment]
Looks like there is a conflict here:

```
The conflict is caused by:
    censys 2.2.6 depends on urllib3<3.0.0
    pyppeteer 1.0.2 depends on urllib3<2.0.0 and >=1.25.8
    requests 2.31.0 depends on urllib3<3 and >=1.21.1
    types-requests 2.31.0.7 depends on urllib3>=2
```

I can make the pinned version of `types-requests` less demanding.

**Comment by thehappydinoa** [comment]
Now it is erroring out on the following module: `otxsearch`

**Comment by L1ghtn1ng** [comment]
I am getting no results at all for any domain that I try

**Comment by L1ghtn1ng** [comment]
@thehappydinoa seems something is still not working correctly

**Comment by thehappydinoa** [comment]
Thats so strange, what error are you encountering?

**Comment by L1ghtn1ng** [comment]
Getting no errors whatsoever and can see that it’s not even hitting my api usage either

On 8 Oct 2023, at 20:59, Aidan Holland ***@***.***> wrote:

﻿

Thats so strange, what error are you encountering?

**Comment by L1ghtn1ng** [comment]
@thehappydinoa have merged it as it should improve things but but was not working for me but will check again, but if you would not mind checking on your end that would be greatly appreciated. I was not getting any errors at all and from looking in the dashboard getting no hits on my api key either.

**Pull request merged**
