### PR TITLE
Simplify `unique` method in myParser

### LINKED ISSUE #316: Rework of unique method inside myparser.py
Inside theHarvester/parsers, the method unique inside myparser.py could use reworking as it is convoluted and could be improved upon.

### PR DESCRIPTION
**Pull request by cueo**
Fix #316

### CODE REVIEW

**Comment by cueo** [comment]
@NotoriousRebel is the order important for the `unique()` method?

**Comment by NotoriousRebel** [comment]
@cueo Your changes look good! You should cast to a set before you cast to a list as a set is that makes the values unique ;) Will merge soon.

**Comment by L1ghtn1ng** [comment]
@cueo Can you rebase this please as this PR has merge conflicts

**Comment by L1ghtn1ng** [comment]
Also please implement @NotoriousRebel changes, thanks

**Comment by cueo** [comment]
@L1ghtn1ng I have rebased the PR.
Also, I don't think @NotoriousRebel requested any changes, he mentioned that in order to make values unique I should cast to a `set` first which is what I am doing. Is it okay to be merged now?
Thanks!

**Comment by cueo** [comment]
> @cueo Your changes look good! You should cast to a set before you cast to a list as a set is what makes the values unique ;) Will merge soon.

@NotoriousRebel One thing that we should be wary about is order of elements in `self.temp` might change on casting it to a `set`.

**Comment by L1ghtn1ng** [comment]
It needs to be set then list not the other way round. That is what @NotoriousRebel was getting at?
________________________________

**Comment by cueo** [comment]
@L1ghtn1ng that's what I have done. Not sure if I'm missing something here.

`self.temp` is first cast to a set -> `set(self.temp)`
since we need to return a list, we convert that set to list -> `list(set(self.temp))`

**Comment by L1ghtn1ng** [comment]
Ah okay now that makes sense to me it was ```list(set(self.temp))``` that was throwing me off

**Pull request merged**
