### PR TITLE
Added setup.py

### PR DESCRIPTION
**Pull request by fproldan**
Setup added In order to make the library pip installable.

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
Thanks for the PR this is being looked at!

**Comment by L1ghtn1ng** [comment]
@fproldan Can you please do another merge of master in to this branch please and @laramies once @fproldan has done this can you then please kick a travis build for this branch please, thanks

**Comment by YashvirGit** [comment]
Please help me Im trying to install this through Terminal 

I get this 

Traceback (most recent call last):
  File "./theHarvester.py", line 3, in <module>
    from discovery import *
  File "/root/Desktop/theHarvester/discovery/shodansearch.py", line 3, in <module>
    from shodan import Shodan
ModuleNotFoundError: No module named 'shodan'

**Comment by fproldan** [comment]
@laramies The merge from master was done.

**Comment by fproldan** [comment]
@YashvirGit You should install the [requirements](https://github.com/laramies/theHarvester/blob/master/requirements.txt).

**Comment by YashvirGit** [comment]
@fproldan thanks for the quick reply buddy 
I checked and I already have shodan>=1.11.1 installed
I also set my Shodan API Keys successfully 

I have python 2.7 ? Is that causing the problem Shall I upgrade

**Comment by fproldan** [comment]
@YashvirGit Yes, please read the dependencies section in the readme of the repository.
This is a Pull request, for further questions you should create an issue. Greetings

**Comment by YashvirGit** [comment]
root@kali:~/Desktop/theHarvester# chmod +x theHarvester.py
root@kali:~/Desktop/theHarvester# ls
api-keys.yaml  discovery   LICENSES   requirements.txt  wordlists
changelog.txt  Dockerfile  parsers    tests
COPYING        lib         README.md  theHarvester.py
root@kali:~/Desktop/theHarvester# ./theHarvester.py
Traceback (most recent call last):
  File "./theHarvester.py", line 3, in <module>
    from discovery import *
  File "/root/Desktop/theHarvester/discovery/baidusearch.py", line 2, in <module>
    from lib.core import *
  File "/root/Desktop/theHarvester/lib/core.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Pull request merged**
