### PR TITLE
qwant search engine discovery: fix warning incorrect mimetype

### PR DESCRIPTION
**Pull request by KernelPan1k**
Here's a quick fix for that PR: https://github.com/laramies/theHarvester/pull/504

I don't understand why I didn't get the error messages before.

https://github.com/aio-libs/aiohttp/issues/815

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
getting this on the CI run 
image

**Comment by L1ghtn1ng** [comment]
@KernelPan1k can confirm that it fixes the test issue and when running the module but the issue is that it does not find anything now or if it does only an email that is it, no urls etc, nothing for apple.com,microsoft.com etc any of the big companies nothing gets returned

**Comment by L1ghtn1ng** [comment]
@KernelPan1k You ready for this to be merged?

**Comment by KernelPan1k** [comment]
Yes, I think that this time the code seems to be executing correctly, I don't have any errors at home. For the yale.edu domain, Qwant seems to find emails that are not found by the other services, even if globally this search engine seems to give less results. Please forgive me for the unexpected and errors encountered. Thank you for your patience!

**Comment by L1ghtn1ng** [comment]
No problem and thank you for getting back to me and fixing the issues

**Pull request merged**
