### PR TITLE
Small email improvement

### PR DESCRIPTION
**Pull request by Th4nat0s**
Hello,  a small contribution.

change the regex to avoid invalid results like "@mydomain.com" without private part.
add "| uniq | sort" to email list to avoid duplicates in results.
add -m switch for people who only needs emails :) ...

Still need a "lower(email)" somewhere....

Bye.

### CODE REVIEW

**Comment by laramies** [comment]
Thanks for this, I will look for this in detail soon.

**Comment by tambry** [comment]
"soon"?

**Comment by laramies** [comment]
Hi, I pushed myparser.py changes in Master (removed * and () ) as it was producing lot's of dirty results in my tests.  Regarding the email only, I can add a switch for the output printing only, as the host extraction it virtually doesn't take any time.  Will that do it?   (I couldn't pull this changes into master, thus why I made them myself)

**Comment by Th4nat0s** [comment]
I see conflict do you need another merge request ?

**Comment by laramies** [comment]
Please do a merge request for the e-mail only option, please. :)

**Comment by Th4nat0s** [comment]
Do you mean only the -m "option".. ?? but i'm really interested  (WANT IT in fact :)… ) by the | sort | uniq.. may i implement it in "-m" ... ?

**Comment by laramies** [comment]
If by sort | uniq you mean    `all_emails = sorted(set(all_emails))`  I already added that.  I was referring to `-m`

**Comment by leebaird** [comment]
First, second, and fourth requests have been added.

**Comment by laramies** [comment]
Closing as most request are implemented, except to the option to retrieve the emails only, which I dont think is needed, you can export to XML and grab the emails.

**Pull request closed without merging**
