### PR TITLE
Bing search with at symbol

### LINKED ISSUE #177: Bing search with at symbol
Hello.
I found that theHarvester tool uses such requests to retrieve domain info through bing: '@domain.com'.
It's doesn't find anything for my researches. But I found that for google search it uses such search: '@"domain.com"'. I tried to modify bing search - and yes it shows me much bigger search result.

What do you thinking about? May we can improve that.

### PR DESCRIPTION
**Pull request by YuriyPobezhymov**
This fixes #177.

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
Thanks for the PR, this is being looked at!

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel @YuriyPobezhymov I have done a PR with this fix in plus a few other changes so we can close this this PR as mine supersedes it

**Comment by L1ghtn1ng** [comment]
@YuriyPobezhymov @NotoriousRebel I have updated my PR with other changes as well

**Comment by L1ghtn1ng** [comment]
@YuriyPobezhymov We have found that in some instances that the change that has been merged produces less results that what we have now. I have been discussing internally a solution that should solve this once and for all with @NotoriousRebel

**Comment by YuriyPobezhymov** [comment]
OK

**Pull request closed without merging**
