### PR TITLE
Added Pipfile

### LINKED ISSUE #318: Create Pipfile
For people who like to use pyenv or for other reasons there should be a Pipfile for dependencies.

### PR DESCRIPTION
**Pull request by may55**
Created a pipfile with the help of requirement.txt
Fixes #318

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
@may55 Thank you for the PR! The pipfile looks great, will merge soon. Just out of curiousity did you manually create?

**Comment by may55** [comment]
@NotoriousRebel  No, I have created a virtual environment using _requirements.txt_ and then updated the Pipfile using `pipenv` module.If you don't know about it then go through **Installation and Basic usage** on [this](https://towardsdatascience.com/all-you-need-to-know-about-python-virtual-environments-9b4aae690f97#3d62) link.

**Comment by NotoriousRebel** [comment]
Thanks! Shouldn't you also add the pipfile.lock then I have seen projects that use pipfiles and they always include the lock file.

**Comment by L1ghtn1ng** [comment]
Yeah please add the pip.lock file then me or @NotoriousRebel will merge it

**Comment by L1ghtn1ng** [comment]
Also you can remove the censys python lib as this will not be needed going forward and its not currently used anway. For context please see #312

**Comment by L1ghtn1ng** [comment]
@may55 Can you update the deps to the latest versions please, then I will merge once done. Thanks

**Comment by may55** [comment]
@L1ghtn1ng  So should I upgrade all the modules to the latest version? or just update requirements.txt Pipfile and Pipfile.lock

**Comment by L1ghtn1ng** [comment]
Can you please just do Pipfile and Pipfile.lock thanks

**Comment by may55** [comment]
Yeah, that's done!

**Comment by L1ghtn1ng** [comment]
Also sorry forgot to mention can you update the pip files with the latest release of the deps please. Do not worry about the requirements.txt as I have that taken care off in my WIP PR

**Comment by may55** [comment]
@L1ghtn1ng So I have to update all the dependencies to their latest version and then make pipfiles accordingly right?

**Comment by L1ghtn1ng** [comment]
Yes

________________________________

**Pull request closed without merging**
