### PR TITLE
Fix missing dependences

### PR DESCRIPTION
**Pull request by Edu4rdSHL**
The `pytz` and `decorator` python libraries are misisng from deps-

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
Have you gotten an error about these libraries missing?

**Comment by leebaird** [comment]
Please place those in alphabetical order.

**Comment by Edu4rdSHL** [comment]
> Have you gotten an error about these libraries missing?

Yes.

**Comment by Edu4rdSHL** [comment]
> Please place those in alphabetical order.

Done.

**Pull request merged**
