### PR TITLE
Reverse dns lookup

### PR DESCRIPTION
**Pull request by moodule**
A simple reverse DNS lookup.
Can be called with the '-n' option.

*Note*
The `__main__.py` hasn't been modified.
IE the functionality is here but the results are *not* added to the report.
As is `__main__.py` only prints the results (l 460-488).

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
@moodule Please take care of the Travis build not passing you can solve it by using autopep8 or since the issue is rather small just read the Travis build output and do what it says. Furthermore, resolve the alert raised by lgtm.

**Comment by moodule** [comment]
hahaha this is unfair!!!
I'm actually using the original naming! like the method 'self.list' which is obviously so ambiguous!

**Comment by moodule** [comment]
this has been messy~

it's ironic, cause my first reaction was "resist the urge to lint / factor" just flow,  and now it blows in my face! :D

anyway~ i hope the logic is valid and it helps a bit!!

**Comment by NotoriousRebel** [comment]
@moodule This looks great and I will test it tomorrow. However, if this was to be merged in its current state it would be immediately rewritten. Why? Because the entire codebase is being refactored to by fully asynchronous. I encourage you to check out hostchecker.py and see how that is implemented as well as [aiodns](https://github.com/saghul/aiodns) documentation. Lastly, please look [here](https://github.com/saghul/aiodns) for docstring conventions specifically in regards to functions. If you need any help or have questions feel free to ask.

**Comment by moodule** [comment]
Alright I'll follow the async style of @L1ghtn1ng :+1: 

I'll do it for DNS brute force and TLD expansion while I'm at it.

**Comment by moodule** [comment]
Btw @NotoriousRebel [saghul/aiodns](https://github.com/saghul/aiodns) looks empty?!
There's close to no code and no docstrings at all :grinning: 

I saw that there was little docstrings here and I took the liberty to format it as [numpy docstrings](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).
I shoulda asked, sorry!

Buuuut it's widely used and I find it more readable because of the spacing & indentation.
What do you think?

**Comment by moodule** [comment]
Thanks for reading the PR @NotoriousRebel !

How soon are we talking for the full async refactoring?
May-be I should directly put my PR in @L1ghtn1ng 's fork?

**Comment by L1ghtn1ng** [comment]
That would be the best idea as it will be soon

________________________________

**Comment by L1ghtn1ng** [comment]
Closing this out as please do a PR to my for in my dev branch and this will then be added in #383 when it is merged

**Pull request closed without merging**
