### PR TITLE
chore(deps): Update censys

### PR DESCRIPTION
**Pull request by thehappydinoa**
- Updated Censys package
- Added emails to the Censys module

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
@thehappydinoa Thanks for this, was banging my head getting this updated. I have copied your changes in my branch https://github.com/L1ghtn1ng/theHarvester/commit/b2376857b889a9f6dbf2a3822b1bea0bcea94118 and also added a change that you have missed as well. Reason being I am not merging this in to master is that we will be doing a new major release soon and do not want any conflicts with PR's and the work that I am doing. Thanks again for this 👍🏻

**Comment by thehappydinoa** [comment]
Sounds good @L1ghtn1ng, thanks for keeping me updated! Also let me know if there is anything I can do to make future updates easier.

**Comment by L1ghtn1ng** [comment]
If there is any breaking changes with the censys SDK coming would be good to have things updated for the release of the SDK going forward 👍

**Comment by thehappydinoa** [comment]
Yeah absolutely, in this last update we changed to use a namespace package which broke a lot of imports, it shouldn't happen again haha

**Pull request closed without merging**
